Fix TON compilation on Windows (github only)
ton-blockchain/ton pull request #1020
Opened 2024-06-11 10:05 UTC by neodix42

With a new OS image runner update for Windows Server 2022, libsodium library behaves weirdly and compilation cannot proceed. At the same time on other Windows machines, it works fine. A temporary solution is to switch to an older Windows image runner.

2024-06-22 07:18 UTC, awesome-doge approved these changes
Test passed

<img width="799" alt="截圖 2024-06-22 下午3 16 42" src="https://github.com/ton-blockchain/ton/assets/54278075/221b566c-128f-4054-a2e3-f29ed3516e93">

2024-06-22 07:54 UTC, awesome-doge commented
There is nothing wrong with your @neodix42 code

But the server of download.libsodium.org is not stable

There is about a 1/2 chance that the compilation will fail because download.libsodium.org cannot be downloaded.

I think we can add some code that attempts to reinstall libsodium to improve the stability of the code.

<img width="1100" alt="截圖 2024-06-22 下午3 51 05" src="https://github.com/ton-blockchain/ton/assets/54278075/dd355990-be93-4c1d-bdd7-774eece98485">

2024-06-22 08:00 UTC, neodix42 commented
Hi awesomedoge,
No, there is definitely an issue with the latest github windows runner. The problem with download.libsodium.org is just an unpleasant rendezvous with comparison to that.

2024-06-22 08:15 UTC, awesome-doge requested changes

2024-06-22 08:15 UTC, awesome-doge commented on assembly/native/build-windows-2019.bat
> +curl  -Lo libsodium-1.0.18-stable-msvc.zip https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-msvc.zip
```suggestion
curl --retry 5 --retry-delay 10 -Lo libsodium-1.0.18-stable-msvc.zip https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-msvc.zip
```

2024-06-24 14:08 UTC, EmelyanenkoK approved these changes

2024-06-24 14:09 UTC, merged